name: Greeting

on: [push, pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # oder eine spezifische Python-Version

    - name: Run greeting script
      run: |
        python greet.py
